# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-17 03:26
from __future__ import unicode_literals

from django.db import migrations, models

# Database migrations are essentially version control for databases.
class Migration(migrations.Migration):

    initial = True # first migration (no migrations before it)

    dependencies = [ # lists what database migrations should have happened first before this migration happened and what operations happened
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
